version: '3.8'

services:
  nginx:
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

  frontend:
    expose:
      - "3000"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    expose:
      - "8080"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/migrations:/docker-entrypoint-initdb.d
    expose:
      - "5432"
    networks:
      - app-network

volumes:
  postgres_data:
  certbot-etc:
  certbot-var:
  webroot-path:

networks:
  app-network:
    driver: bridge