version: '3.8'

services:
  nginx:
    build:
      dockerfile: nginx/Dockerfile.dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/app  # Mount frontend source for development
    command: /bin/sh -c "nginx -g 'daemon off;'"

  backend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/virusscanner?sslmode=disable
    command: go run main.go
    depends_on:
      - db

  # DB service only in development
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/migrations:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=filescanner
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data: