version: '3.8'

services:
  nginx:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf:ro

  frontend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env.dev
    command: npm start

  backend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    env_file:
      - .env.dev
    command: go run main.go

  db:
    env_file:
      - .env.dev
    ports:
      - "5432:5432" 