version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    expose:
      - "8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge