services:
  nginx:
    image: ${ECR_REGISTRY}/virusscanner-frontend:${IMAGE_TAG}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    restart: always

  backend:
    image: ${ECR_REGISTRY}/virusscanner-backend:${IMAGE_TAG}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    env_file:
      - .env
    restart: always